version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/petal-labs/petalflow

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - gocritic
    - gosec
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    govet:
      enable-all: true
    misspell:
      locale: US
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
