version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
  exclusions:
    paths:
      - examples
      - ".*_test\\.go"
  settings:
    govet:
      disable:
        - fieldalignment

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/petal-labs/petalflow

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
