/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkflowsIndexRouteImport } from './routes/_app/workflows/index'
import { Route as AppToolsIndexRouteImport } from './routes/_app/tools/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppRunsIndexRouteImport } from './routes/_app/runs/index'
import { Route as AppProvidersIndexRouteImport } from './routes/_app/providers/index'
import { Route as AppDesignerIndexRouteImport } from './routes/_app/designer/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkflowsIndexRoute = AppWorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsIndexRoute = AppToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppRunsIndexRoute = AppRunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => AppRoute,
} as any)
const AppProvidersIndexRoute = AppProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => AppRoute,
} as any)
const AppDesignerIndexRoute = AppDesignerIndexRouteImport.update({
  id: '/designer/',
  path: '/designer/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/designer/': typeof AppDesignerIndexRoute
  '/providers/': typeof AppProvidersIndexRoute
  '/runs/': typeof AppRunsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/tools/': typeof AppToolsIndexRoute
  '/workflows/': typeof AppWorkflowsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/designer': typeof AppDesignerIndexRoute
  '/providers': typeof AppProvidersIndexRoute
  '/runs': typeof AppRunsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/tools': typeof AppToolsIndexRoute
  '/workflows': typeof AppWorkflowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/designer/': typeof AppDesignerIndexRoute
  '/_app/providers/': typeof AppProvidersIndexRoute
  '/_app/runs/': typeof AppRunsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/tools/': typeof AppToolsIndexRoute
  '/_app/workflows/': typeof AppWorkflowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/designer/'
    | '/providers/'
    | '/runs/'
    | '/settings/'
    | '/tools/'
    | '/workflows/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/designer'
    | '/providers'
    | '/runs'
    | '/settings'
    | '/tools'
    | '/workflows'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/designer/'
    | '/_app/providers/'
    | '/_app/runs/'
    | '/_app/settings/'
    | '/_app/tools/'
    | '/_app/workflows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workflows/': {
      id: '/_app/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof AppWorkflowsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools/': {
      id: '/_app/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof AppToolsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/runs/': {
      id: '/_app/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof AppRunsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/providers/': {
      id: '/_app/providers/'
      path: '/providers'
      fullPath: '/providers/'
      preLoaderRoute: typeof AppProvidersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/designer/': {
      id: '/_app/designer/'
      path: '/designer'
      fullPath: '/designer/'
      preLoaderRoute: typeof AppDesignerIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDesignerIndexRoute: typeof AppDesignerIndexRoute
  AppProvidersIndexRoute: typeof AppProvidersIndexRoute
  AppRunsIndexRoute: typeof AppRunsIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppToolsIndexRoute: typeof AppToolsIndexRoute
  AppWorkflowsIndexRoute: typeof AppWorkflowsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDesignerIndexRoute: AppDesignerIndexRoute,
  AppProvidersIndexRoute: AppProvidersIndexRoute,
  AppRunsIndexRoute: AppRunsIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppToolsIndexRoute: AppToolsIndexRoute,
  AppWorkflowsIndexRoute: AppWorkflowsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
